# Generated by Django 3.2.13 on 2022-09-01 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acticle',
            new_name='Article',
        ),
    ]
